// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// APITokensColumns holds the columns for the "api_tokens" table.
	APITokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "token_hash", Type: field.TypeString, Unique: true},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_used", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_api_tokens", Type: field.TypeInt},
	}
	// APITokensTable holds the schema information for the "api_tokens" table.
	APITokensTable = &schema.Table{
		Name:       "api_tokens",
		Columns:    APITokensColumns,
		PrimaryKey: []*schema.Column{APITokensColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "api_tokens_users_api_tokens",
				Columns:    []*schema.Column{APITokensColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// CategoriesColumns holds the columns for the "categories" table.
	CategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 50},
		{Name: "icon", Type: field.TypeString, Nullable: true, Size: 50, Default: "category"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "household_categories", Type: field.TypeInt},
	}
	// CategoriesTable holds the schema information for the "categories" table.
	CategoriesTable = &schema.Table{
		Name:       "categories",
		Columns:    CategoriesColumns,
		PrimaryKey: []*schema.Column{CategoriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "categories_households_categories",
				Columns:    []*schema.Column{CategoriesColumns[5]},
				RefColumns: []*schema.Column{HouseholdsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "category_name_household_categories",
				Unique:  true,
				Columns: []*schema.Column{CategoriesColumns[1], CategoriesColumns[5]},
			},
		},
	}
	// HouseholdsColumns holds the columns for the "households" table.
	HouseholdsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "currency", Type: field.TypeString, Size: 3, Default: "EUR"},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 500, Default: ""},
		{Name: "icon", Type: field.TypeString, Nullable: true, Size: 50, Default: "home"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_households", Type: field.TypeInt},
	}
	// HouseholdsTable holds the schema information for the "households" table.
	HouseholdsTable = &schema.Table{
		Name:       "households",
		Columns:    HouseholdsColumns,
		PrimaryKey: []*schema.Column{HouseholdsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "households_users_households",
				Columns:    []*schema.Column{HouseholdsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// RecurringExpensesColumns holds the columns for the "recurring_expenses" table.
	RecurringExpensesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 500, Default: ""},
		{Name: "amount", Type: field.TypeString},
		{Name: "frequency", Type: field.TypeString},
		{Name: "active", Type: field.TypeBool, Default: true},
		{Name: "start_date", Type: field.TypeTime},
		{Name: "end_date", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "category_recurring_expenses", Type: field.TypeInt},
		{Name: "household_recurring_expenses", Type: field.TypeInt},
	}
	// RecurringExpensesTable holds the schema information for the "recurring_expenses" table.
	RecurringExpensesTable = &schema.Table{
		Name:       "recurring_expenses",
		Columns:    RecurringExpensesColumns,
		PrimaryKey: []*schema.Column{RecurringExpensesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "recurring_expenses_categories_recurring_expenses",
				Columns:    []*schema.Column{RecurringExpensesColumns[10]},
				RefColumns: []*schema.Column{CategoriesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "recurring_expenses_households_recurring_expenses",
				Columns:    []*schema.Column{RecurringExpensesColumns[11]},
				RefColumns: []*schema.Column{HouseholdsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TransactionsColumns holds the columns for the "transactions" table.
	TransactionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "amount", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "date", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "category_transactions", Type: field.TypeInt},
		{Name: "household_transactions", Type: field.TypeInt},
	}
	// TransactionsTable holds the schema information for the "transactions" table.
	TransactionsTable = &schema.Table{
		Name:       "transactions",
		Columns:    TransactionsColumns,
		PrimaryKey: []*schema.Column{TransactionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "transactions_categories_transactions",
				Columns:    []*schema.Column{TransactionsColumns[6]},
				RefColumns: []*schema.Column{CategoriesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "transactions_households_transactions",
				Columns:    []*schema.Column{TransactionsColumns[7]},
				RefColumns: []*schema.Column{HouseholdsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "transaction_date_household_transactions",
				Unique:  false,
				Columns: []*schema.Column{TransactionsColumns[3], TransactionsColumns[7]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "subject", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		APITokensTable,
		CategoriesTable,
		HouseholdsTable,
		RecurringExpensesTable,
		TransactionsTable,
		UsersTable,
	}
)

func init() {
	APITokensTable.ForeignKeys[0].RefTable = UsersTable
	CategoriesTable.ForeignKeys[0].RefTable = HouseholdsTable
	HouseholdsTable.ForeignKeys[0].RefTable = UsersTable
	RecurringExpensesTable.ForeignKeys[0].RefTable = CategoriesTable
	RecurringExpensesTable.ForeignKeys[1].RefTable = HouseholdsTable
	TransactionsTable.ForeignKeys[0].RefTable = CategoriesTable
	TransactionsTable.ForeignKeys[1].RefTable = HouseholdsTable
}
