// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"icekalt.dev/money-tracker/ent/apitoken"
	"icekalt.dev/money-tracker/ent/user"
)

// APITokenCreate is the builder for creating a APIToken entity.
type APITokenCreate struct {
	config
	mutation *APITokenMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *APITokenCreate) SetName(v string) *APITokenCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetTokenHash sets the "token_hash" field.
func (_c *APITokenCreate) SetTokenHash(v string) *APITokenCreate {
	_c.mutation.SetTokenHash(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *APITokenCreate) SetExpiresAt(v time.Time) *APITokenCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *APITokenCreate) SetNillableExpiresAt(v *time.Time) *APITokenCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetLastUsed sets the "last_used" field.
func (_c *APITokenCreate) SetLastUsed(v time.Time) *APITokenCreate {
	_c.mutation.SetLastUsed(v)
	return _c
}

// SetNillableLastUsed sets the "last_used" field if the given value is not nil.
func (_c *APITokenCreate) SetNillableLastUsed(v *time.Time) *APITokenCreate {
	if v != nil {
		_c.SetLastUsed(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *APITokenCreate) SetCreatedAt(v time.Time) *APITokenCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *APITokenCreate) SetNillableCreatedAt(v *time.Time) *APITokenCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *APITokenCreate) SetUserID(id int) *APITokenCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *APITokenCreate) SetUser(v *User) *APITokenCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the APITokenMutation object of the builder.
func (_c *APITokenCreate) Mutation() *APITokenMutation {
	return _c.mutation
}

// Save creates the APIToken in the database.
func (_c *APITokenCreate) Save(ctx context.Context) (*APIToken, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *APITokenCreate) SaveX(ctx context.Context) *APIToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *APITokenCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *APITokenCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *APITokenCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := apitoken.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *APITokenCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "APIToken.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := apitoken.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "APIToken.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TokenHash(); !ok {
		return &ValidationError{Name: "token_hash", err: errors.New(`ent: missing required field "APIToken.token_hash"`)}
	}
	if v, ok := _c.mutation.TokenHash(); ok {
		if err := apitoken.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "APIToken.token_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "APIToken.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "APIToken.user"`)}
	}
	return nil
}

func (_c *APITokenCreate) sqlSave(ctx context.Context) (*APIToken, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *APITokenCreate) createSpec() (*APIToken, *sqlgraph.CreateSpec) {
	var (
		_node = &APIToken{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(apitoken.Table, sqlgraph.NewFieldSpec(apitoken.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(apitoken.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.TokenHash(); ok {
		_spec.SetField(apitoken.FieldTokenHash, field.TypeString, value)
		_node.TokenHash = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(apitoken.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.LastUsed(); ok {
		_spec.SetField(apitoken.FieldLastUsed, field.TypeTime, value)
		_node.LastUsed = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(apitoken.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apitoken.UserTable,
			Columns: []string{apitoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_api_tokens = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// APITokenCreateBulk is the builder for creating many APIToken entities in bulk.
type APITokenCreateBulk struct {
	config
	err      error
	builders []*APITokenCreate
}

// Save creates the APIToken entities in the database.
func (_c *APITokenCreateBulk) Save(ctx context.Context) ([]*APIToken, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*APIToken, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*APITokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *APITokenCreateBulk) SaveX(ctx context.Context) []*APIToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *APITokenCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *APITokenCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
