// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"icekalt.dev/money-tracker/ent/household"
	"icekalt.dev/money-tracker/ent/user"
)

// Household is the model entity for the Household schema.
type Household struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// Icon holds the value of the "icon" field.
	Icon string `json:"icon,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the HouseholdQuery when eager-loading is set.
	Edges           HouseholdEdges `json:"edges"`
	user_households *int
	selectValues    sql.SelectValues
}

// HouseholdEdges holds the relations/edges for other nodes in the graph.
type HouseholdEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// Categories holds the value of the categories edge.
	Categories []*Category `json:"categories,omitempty"`
	// Transactions holds the value of the transactions edge.
	Transactions []*Transaction `json:"transactions,omitempty"`
	// RecurringExpenses holds the value of the recurring_expenses edge.
	RecurringExpenses []*RecurringExpense `json:"recurring_expenses,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e HouseholdEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// CategoriesOrErr returns the Categories value or an error if the edge
// was not loaded in eager-loading.
func (e HouseholdEdges) CategoriesOrErr() ([]*Category, error) {
	if e.loadedTypes[1] {
		return e.Categories, nil
	}
	return nil, &NotLoadedError{edge: "categories"}
}

// TransactionsOrErr returns the Transactions value or an error if the edge
// was not loaded in eager-loading.
func (e HouseholdEdges) TransactionsOrErr() ([]*Transaction, error) {
	if e.loadedTypes[2] {
		return e.Transactions, nil
	}
	return nil, &NotLoadedError{edge: "transactions"}
}

// RecurringExpensesOrErr returns the RecurringExpenses value or an error if the edge
// was not loaded in eager-loading.
func (e HouseholdEdges) RecurringExpensesOrErr() ([]*RecurringExpense, error) {
	if e.loadedTypes[3] {
		return e.RecurringExpenses, nil
	}
	return nil, &NotLoadedError{edge: "recurring_expenses"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Household) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case household.FieldID:
			values[i] = new(sql.NullInt64)
		case household.FieldName, household.FieldCurrency, household.FieldIcon:
			values[i] = new(sql.NullString)
		case household.FieldCreatedAt, household.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case household.ForeignKeys[0]: // user_households
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Household fields.
func (_m *Household) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case household.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case household.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case household.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case household.FieldIcon:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field icon", values[i])
			} else if value.Valid {
				_m.Icon = value.String
			}
		case household.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case household.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case household.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_households", value)
			} else if value.Valid {
				_m.user_households = new(int)
				*_m.user_households = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Household.
// This includes values selected through modifiers, order, etc.
func (_m *Household) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the Household entity.
func (_m *Household) QueryOwner() *UserQuery {
	return NewHouseholdClient(_m.config).QueryOwner(_m)
}

// QueryCategories queries the "categories" edge of the Household entity.
func (_m *Household) QueryCategories() *CategoryQuery {
	return NewHouseholdClient(_m.config).QueryCategories(_m)
}

// QueryTransactions queries the "transactions" edge of the Household entity.
func (_m *Household) QueryTransactions() *TransactionQuery {
	return NewHouseholdClient(_m.config).QueryTransactions(_m)
}

// QueryRecurringExpenses queries the "recurring_expenses" edge of the Household entity.
func (_m *Household) QueryRecurringExpenses() *RecurringExpenseQuery {
	return NewHouseholdClient(_m.config).QueryRecurringExpenses(_m)
}

// Update returns a builder for updating this Household.
// Note that you need to call Household.Unwrap() before calling this method if this Household
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Household) Update() *HouseholdUpdateOne {
	return NewHouseholdClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Household entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Household) Unwrap() *Household {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Household is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Household) String() string {
	var builder strings.Builder
	builder.WriteString("Household(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("icon=")
	builder.WriteString(_m.Icon)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Households is a parsable slice of Household.
type Households []*Household
