// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"icekalt.dev/money-tracker/ent/predicate"
	"icekalt.dev/money-tracker/ent/recurringscheduleoverride"
)

// RecurringScheduleOverrideDelete is the builder for deleting a RecurringScheduleOverride entity.
type RecurringScheduleOverrideDelete struct {
	config
	hooks    []Hook
	mutation *RecurringScheduleOverrideMutation
}

// Where appends a list predicates to the RecurringScheduleOverrideDelete builder.
func (_d *RecurringScheduleOverrideDelete) Where(ps ...predicate.RecurringScheduleOverride) *RecurringScheduleOverrideDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RecurringScheduleOverrideDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RecurringScheduleOverrideDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RecurringScheduleOverrideDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(recurringscheduleoverride.Table, sqlgraph.NewFieldSpec(recurringscheduleoverride.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RecurringScheduleOverrideDeleteOne is the builder for deleting a single RecurringScheduleOverride entity.
type RecurringScheduleOverrideDeleteOne struct {
	_d *RecurringScheduleOverrideDelete
}

// Where appends a list predicates to the RecurringScheduleOverrideDelete builder.
func (_d *RecurringScheduleOverrideDeleteOne) Where(ps ...predicate.RecurringScheduleOverride) *RecurringScheduleOverrideDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RecurringScheduleOverrideDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{recurringscheduleoverride.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RecurringScheduleOverrideDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
