// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"icekalt.dev/money-tracker/ent/category"
	"icekalt.dev/money-tracker/ent/household"
	"icekalt.dev/money-tracker/ent/recurringexpense"
)

// RecurringExpenseCreate is the builder for creating a RecurringExpense entity.
type RecurringExpenseCreate struct {
	config
	mutation *RecurringExpenseMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *RecurringExpenseCreate) SetName(v string) *RecurringExpenseCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *RecurringExpenseCreate) SetAmount(v string) *RecurringExpenseCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetFrequency sets the "frequency" field.
func (_c *RecurringExpenseCreate) SetFrequency(v string) *RecurringExpenseCreate {
	_c.mutation.SetFrequency(v)
	return _c
}

// SetActive sets the "active" field.
func (_c *RecurringExpenseCreate) SetActive(v bool) *RecurringExpenseCreate {
	_c.mutation.SetActive(v)
	return _c
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_c *RecurringExpenseCreate) SetNillableActive(v *bool) *RecurringExpenseCreate {
	if v != nil {
		_c.SetActive(*v)
	}
	return _c
}

// SetStartDate sets the "start_date" field.
func (_c *RecurringExpenseCreate) SetStartDate(v time.Time) *RecurringExpenseCreate {
	_c.mutation.SetStartDate(v)
	return _c
}

// SetEndDate sets the "end_date" field.
func (_c *RecurringExpenseCreate) SetEndDate(v time.Time) *RecurringExpenseCreate {
	_c.mutation.SetEndDate(v)
	return _c
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_c *RecurringExpenseCreate) SetNillableEndDate(v *time.Time) *RecurringExpenseCreate {
	if v != nil {
		_c.SetEndDate(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RecurringExpenseCreate) SetCreatedAt(v time.Time) *RecurringExpenseCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RecurringExpenseCreate) SetNillableCreatedAt(v *time.Time) *RecurringExpenseCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RecurringExpenseCreate) SetUpdatedAt(v time.Time) *RecurringExpenseCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RecurringExpenseCreate) SetNillableUpdatedAt(v *time.Time) *RecurringExpenseCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetHouseholdID sets the "household" edge to the Household entity by ID.
func (_c *RecurringExpenseCreate) SetHouseholdID(id int) *RecurringExpenseCreate {
	_c.mutation.SetHouseholdID(id)
	return _c
}

// SetHousehold sets the "household" edge to the Household entity.
func (_c *RecurringExpenseCreate) SetHousehold(v *Household) *RecurringExpenseCreate {
	return _c.SetHouseholdID(v.ID)
}

// SetCategoryID sets the "category" edge to the Category entity by ID.
func (_c *RecurringExpenseCreate) SetCategoryID(id int) *RecurringExpenseCreate {
	_c.mutation.SetCategoryID(id)
	return _c
}

// SetCategory sets the "category" edge to the Category entity.
func (_c *RecurringExpenseCreate) SetCategory(v *Category) *RecurringExpenseCreate {
	return _c.SetCategoryID(v.ID)
}

// Mutation returns the RecurringExpenseMutation object of the builder.
func (_c *RecurringExpenseCreate) Mutation() *RecurringExpenseMutation {
	return _c.mutation
}

// Save creates the RecurringExpense in the database.
func (_c *RecurringExpenseCreate) Save(ctx context.Context) (*RecurringExpense, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RecurringExpenseCreate) SaveX(ctx context.Context) *RecurringExpense {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RecurringExpenseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RecurringExpenseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RecurringExpenseCreate) defaults() {
	if _, ok := _c.mutation.Active(); !ok {
		v := recurringexpense.DefaultActive
		_c.mutation.SetActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := recurringexpense.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := recurringexpense.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RecurringExpenseCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "RecurringExpense.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := recurringexpense.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RecurringExpense.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "RecurringExpense.amount"`)}
	}
	if v, ok := _c.mutation.Amount(); ok {
		if err := recurringexpense.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "RecurringExpense.amount": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Frequency(); !ok {
		return &ValidationError{Name: "frequency", err: errors.New(`ent: missing required field "RecurringExpense.frequency"`)}
	}
	if v, ok := _c.mutation.Frequency(); ok {
		if err := recurringexpense.FrequencyValidator(v); err != nil {
			return &ValidationError{Name: "frequency", err: fmt.Errorf(`ent: validator failed for field "RecurringExpense.frequency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "RecurringExpense.active"`)}
	}
	if _, ok := _c.mutation.StartDate(); !ok {
		return &ValidationError{Name: "start_date", err: errors.New(`ent: missing required field "RecurringExpense.start_date"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RecurringExpense.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RecurringExpense.updated_at"`)}
	}
	if len(_c.mutation.HouseholdIDs()) == 0 {
		return &ValidationError{Name: "household", err: errors.New(`ent: missing required edge "RecurringExpense.household"`)}
	}
	if len(_c.mutation.CategoryIDs()) == 0 {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required edge "RecurringExpense.category"`)}
	}
	return nil
}

func (_c *RecurringExpenseCreate) sqlSave(ctx context.Context) (*RecurringExpense, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RecurringExpenseCreate) createSpec() (*RecurringExpense, *sqlgraph.CreateSpec) {
	var (
		_node = &RecurringExpense{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(recurringexpense.Table, sqlgraph.NewFieldSpec(recurringexpense.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(recurringexpense.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(recurringexpense.FieldAmount, field.TypeString, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Frequency(); ok {
		_spec.SetField(recurringexpense.FieldFrequency, field.TypeString, value)
		_node.Frequency = value
	}
	if value, ok := _c.mutation.Active(); ok {
		_spec.SetField(recurringexpense.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if value, ok := _c.mutation.StartDate(); ok {
		_spec.SetField(recurringexpense.FieldStartDate, field.TypeTime, value)
		_node.StartDate = value
	}
	if value, ok := _c.mutation.EndDate(); ok {
		_spec.SetField(recurringexpense.FieldEndDate, field.TypeTime, value)
		_node.EndDate = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(recurringexpense.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(recurringexpense.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.HouseholdIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringexpense.HouseholdTable,
			Columns: []string{recurringexpense.HouseholdColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(household.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.household_recurring_expenses = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringexpense.CategoryTable,
			Columns: []string{recurringexpense.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.category_recurring_expenses = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RecurringExpenseCreateBulk is the builder for creating many RecurringExpense entities in bulk.
type RecurringExpenseCreateBulk struct {
	config
	err      error
	builders []*RecurringExpenseCreate
}

// Save creates the RecurringExpense entities in the database.
func (_c *RecurringExpenseCreateBulk) Save(ctx context.Context) ([]*RecurringExpense, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RecurringExpense, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RecurringExpenseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RecurringExpenseCreateBulk) SaveX(ctx context.Context) []*RecurringExpense {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RecurringExpenseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RecurringExpenseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
