// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"icekalt.dev/money-tracker/ent/predicate"
	"icekalt.dev/money-tracker/ent/recurringexpense"
)

// RecurringExpenseDelete is the builder for deleting a RecurringExpense entity.
type RecurringExpenseDelete struct {
	config
	hooks    []Hook
	mutation *RecurringExpenseMutation
}

// Where appends a list predicates to the RecurringExpenseDelete builder.
func (_d *RecurringExpenseDelete) Where(ps ...predicate.RecurringExpense) *RecurringExpenseDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RecurringExpenseDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RecurringExpenseDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RecurringExpenseDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(recurringexpense.Table, sqlgraph.NewFieldSpec(recurringexpense.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RecurringExpenseDeleteOne is the builder for deleting a single RecurringExpense entity.
type RecurringExpenseDeleteOne struct {
	_d *RecurringExpenseDelete
}

// Where appends a list predicates to the RecurringExpenseDelete builder.
func (_d *RecurringExpenseDeleteOne) Where(ps ...predicate.RecurringExpense) *RecurringExpenseDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RecurringExpenseDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{recurringexpense.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RecurringExpenseDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
