// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"icekalt.dev/money-tracker/ent/category"
	"icekalt.dev/money-tracker/ent/household"
	"icekalt.dev/money-tracker/ent/recurringexpense"
)

// RecurringExpense is the model entity for the RecurringExpense schema.
type RecurringExpense struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount string `json:"amount,omitempty"`
	// Frequency holds the value of the "frequency" field.
	Frequency string `json:"frequency,omitempty"`
	// Active holds the value of the "active" field.
	Active bool `json:"active,omitempty"`
	// StartDate holds the value of the "start_date" field.
	StartDate time.Time `json:"start_date,omitempty"`
	// EndDate holds the value of the "end_date" field.
	EndDate *time.Time `json:"end_date,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RecurringExpenseQuery when eager-loading is set.
	Edges                        RecurringExpenseEdges `json:"edges"`
	category_recurring_expenses  *int
	household_recurring_expenses *int
	selectValues                 sql.SelectValues
}

// RecurringExpenseEdges holds the relations/edges for other nodes in the graph.
type RecurringExpenseEdges struct {
	// Household holds the value of the household edge.
	Household *Household `json:"household,omitempty"`
	// Category holds the value of the category edge.
	Category *Category `json:"category,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// HouseholdOrErr returns the Household value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RecurringExpenseEdges) HouseholdOrErr() (*Household, error) {
	if e.Household != nil {
		return e.Household, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: household.Label}
	}
	return nil, &NotLoadedError{edge: "household"}
}

// CategoryOrErr returns the Category value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RecurringExpenseEdges) CategoryOrErr() (*Category, error) {
	if e.Category != nil {
		return e.Category, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: category.Label}
	}
	return nil, &NotLoadedError{edge: "category"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RecurringExpense) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case recurringexpense.FieldActive:
			values[i] = new(sql.NullBool)
		case recurringexpense.FieldID:
			values[i] = new(sql.NullInt64)
		case recurringexpense.FieldName, recurringexpense.FieldDescription, recurringexpense.FieldAmount, recurringexpense.FieldFrequency:
			values[i] = new(sql.NullString)
		case recurringexpense.FieldStartDate, recurringexpense.FieldEndDate, recurringexpense.FieldCreatedAt, recurringexpense.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case recurringexpense.ForeignKeys[0]: // category_recurring_expenses
			values[i] = new(sql.NullInt64)
		case recurringexpense.ForeignKeys[1]: // household_recurring_expenses
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RecurringExpense fields.
func (_m *RecurringExpense) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case recurringexpense.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case recurringexpense.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case recurringexpense.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case recurringexpense.FieldAmount:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.String
			}
		case recurringexpense.FieldFrequency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field frequency", values[i])
			} else if value.Valid {
				_m.Frequency = value.String
			}
		case recurringexpense.FieldActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field active", values[i])
			} else if value.Valid {
				_m.Active = value.Bool
			}
		case recurringexpense.FieldStartDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start_date", values[i])
			} else if value.Valid {
				_m.StartDate = value.Time
			}
		case recurringexpense.FieldEndDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field end_date", values[i])
			} else if value.Valid {
				_m.EndDate = new(time.Time)
				*_m.EndDate = value.Time
			}
		case recurringexpense.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case recurringexpense.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case recurringexpense.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field category_recurring_expenses", value)
			} else if value.Valid {
				_m.category_recurring_expenses = new(int)
				*_m.category_recurring_expenses = int(value.Int64)
			}
		case recurringexpense.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field household_recurring_expenses", value)
			} else if value.Valid {
				_m.household_recurring_expenses = new(int)
				*_m.household_recurring_expenses = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RecurringExpense.
// This includes values selected through modifiers, order, etc.
func (_m *RecurringExpense) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryHousehold queries the "household" edge of the RecurringExpense entity.
func (_m *RecurringExpense) QueryHousehold() *HouseholdQuery {
	return NewRecurringExpenseClient(_m.config).QueryHousehold(_m)
}

// QueryCategory queries the "category" edge of the RecurringExpense entity.
func (_m *RecurringExpense) QueryCategory() *CategoryQuery {
	return NewRecurringExpenseClient(_m.config).QueryCategory(_m)
}

// Update returns a builder for updating this RecurringExpense.
// Note that you need to call RecurringExpense.Unwrap() before calling this method if this RecurringExpense
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RecurringExpense) Update() *RecurringExpenseUpdateOne {
	return NewRecurringExpenseClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RecurringExpense entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RecurringExpense) Unwrap() *RecurringExpense {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RecurringExpense is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RecurringExpense) String() string {
	var builder strings.Builder
	builder.WriteString("RecurringExpense(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(_m.Amount)
	builder.WriteString(", ")
	builder.WriteString("frequency=")
	builder.WriteString(_m.Frequency)
	builder.WriteString(", ")
	builder.WriteString("active=")
	builder.WriteString(fmt.Sprintf("%v", _m.Active))
	builder.WriteString(", ")
	builder.WriteString("start_date=")
	builder.WriteString(_m.StartDate.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.EndDate; v != nil {
		builder.WriteString("end_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RecurringExpenses is a parsable slice of RecurringExpense.
type RecurringExpenses []*RecurringExpense
