// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"icekalt.dev/money-tracker/ent/category"
	"icekalt.dev/money-tracker/ent/household"
	"icekalt.dev/money-tracker/ent/predicate"
	"icekalt.dev/money-tracker/ent/recurringexpense"
)

// RecurringExpenseUpdate is the builder for updating RecurringExpense entities.
type RecurringExpenseUpdate struct {
	config
	hooks    []Hook
	mutation *RecurringExpenseMutation
}

// Where appends a list predicates to the RecurringExpenseUpdate builder.
func (_u *RecurringExpenseUpdate) Where(ps ...predicate.RecurringExpense) *RecurringExpenseUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *RecurringExpenseUpdate) SetName(v string) *RecurringExpenseUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RecurringExpenseUpdate) SetNillableName(v *string) *RecurringExpenseUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *RecurringExpenseUpdate) SetAmount(v string) *RecurringExpenseUpdate {
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *RecurringExpenseUpdate) SetNillableAmount(v *string) *RecurringExpenseUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// SetFrequency sets the "frequency" field.
func (_u *RecurringExpenseUpdate) SetFrequency(v string) *RecurringExpenseUpdate {
	_u.mutation.SetFrequency(v)
	return _u
}

// SetNillableFrequency sets the "frequency" field if the given value is not nil.
func (_u *RecurringExpenseUpdate) SetNillableFrequency(v *string) *RecurringExpenseUpdate {
	if v != nil {
		_u.SetFrequency(*v)
	}
	return _u
}

// SetActive sets the "active" field.
func (_u *RecurringExpenseUpdate) SetActive(v bool) *RecurringExpenseUpdate {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *RecurringExpenseUpdate) SetNillableActive(v *bool) *RecurringExpenseUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *RecurringExpenseUpdate) SetStartDate(v time.Time) *RecurringExpenseUpdate {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *RecurringExpenseUpdate) SetNillableStartDate(v *time.Time) *RecurringExpenseUpdate {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *RecurringExpenseUpdate) SetEndDate(v time.Time) *RecurringExpenseUpdate {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *RecurringExpenseUpdate) SetNillableEndDate(v *time.Time) *RecurringExpenseUpdate {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// ClearEndDate clears the value of the "end_date" field.
func (_u *RecurringExpenseUpdate) ClearEndDate() *RecurringExpenseUpdate {
	_u.mutation.ClearEndDate()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RecurringExpenseUpdate) SetUpdatedAt(v time.Time) *RecurringExpenseUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetHouseholdID sets the "household" edge to the Household entity by ID.
func (_u *RecurringExpenseUpdate) SetHouseholdID(id int) *RecurringExpenseUpdate {
	_u.mutation.SetHouseholdID(id)
	return _u
}

// SetHousehold sets the "household" edge to the Household entity.
func (_u *RecurringExpenseUpdate) SetHousehold(v *Household) *RecurringExpenseUpdate {
	return _u.SetHouseholdID(v.ID)
}

// SetCategoryID sets the "category" edge to the Category entity by ID.
func (_u *RecurringExpenseUpdate) SetCategoryID(id int) *RecurringExpenseUpdate {
	_u.mutation.SetCategoryID(id)
	return _u
}

// SetCategory sets the "category" edge to the Category entity.
func (_u *RecurringExpenseUpdate) SetCategory(v *Category) *RecurringExpenseUpdate {
	return _u.SetCategoryID(v.ID)
}

// Mutation returns the RecurringExpenseMutation object of the builder.
func (_u *RecurringExpenseUpdate) Mutation() *RecurringExpenseMutation {
	return _u.mutation
}

// ClearHousehold clears the "household" edge to the Household entity.
func (_u *RecurringExpenseUpdate) ClearHousehold() *RecurringExpenseUpdate {
	_u.mutation.ClearHousehold()
	return _u
}

// ClearCategory clears the "category" edge to the Category entity.
func (_u *RecurringExpenseUpdate) ClearCategory() *RecurringExpenseUpdate {
	_u.mutation.ClearCategory()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RecurringExpenseUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RecurringExpenseUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RecurringExpenseUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RecurringExpenseUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RecurringExpenseUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := recurringexpense.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RecurringExpenseUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := recurringexpense.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RecurringExpense.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Amount(); ok {
		if err := recurringexpense.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "RecurringExpense.amount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Frequency(); ok {
		if err := recurringexpense.FrequencyValidator(v); err != nil {
			return &ValidationError{Name: "frequency", err: fmt.Errorf(`ent: validator failed for field "RecurringExpense.frequency": %w`, err)}
		}
	}
	if _u.mutation.HouseholdCleared() && len(_u.mutation.HouseholdIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RecurringExpense.household"`)
	}
	if _u.mutation.CategoryCleared() && len(_u.mutation.CategoryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RecurringExpense.category"`)
	}
	return nil
}

func (_u *RecurringExpenseUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(recurringexpense.Table, recurringexpense.Columns, sqlgraph.NewFieldSpec(recurringexpense.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(recurringexpense.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(recurringexpense.FieldAmount, field.TypeString, value)
	}
	if value, ok := _u.mutation.Frequency(); ok {
		_spec.SetField(recurringexpense.FieldFrequency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(recurringexpense.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(recurringexpense.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(recurringexpense.FieldEndDate, field.TypeTime, value)
	}
	if _u.mutation.EndDateCleared() {
		_spec.ClearField(recurringexpense.FieldEndDate, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(recurringexpense.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.HouseholdCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringexpense.HouseholdTable,
			Columns: []string{recurringexpense.HouseholdColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(household.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HouseholdIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringexpense.HouseholdTable,
			Columns: []string{recurringexpense.HouseholdColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(household.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringexpense.CategoryTable,
			Columns: []string{recurringexpense.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringexpense.CategoryTable,
			Columns: []string{recurringexpense.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{recurringexpense.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RecurringExpenseUpdateOne is the builder for updating a single RecurringExpense entity.
type RecurringExpenseUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RecurringExpenseMutation
}

// SetName sets the "name" field.
func (_u *RecurringExpenseUpdateOne) SetName(v string) *RecurringExpenseUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RecurringExpenseUpdateOne) SetNillableName(v *string) *RecurringExpenseUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *RecurringExpenseUpdateOne) SetAmount(v string) *RecurringExpenseUpdateOne {
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *RecurringExpenseUpdateOne) SetNillableAmount(v *string) *RecurringExpenseUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// SetFrequency sets the "frequency" field.
func (_u *RecurringExpenseUpdateOne) SetFrequency(v string) *RecurringExpenseUpdateOne {
	_u.mutation.SetFrequency(v)
	return _u
}

// SetNillableFrequency sets the "frequency" field if the given value is not nil.
func (_u *RecurringExpenseUpdateOne) SetNillableFrequency(v *string) *RecurringExpenseUpdateOne {
	if v != nil {
		_u.SetFrequency(*v)
	}
	return _u
}

// SetActive sets the "active" field.
func (_u *RecurringExpenseUpdateOne) SetActive(v bool) *RecurringExpenseUpdateOne {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *RecurringExpenseUpdateOne) SetNillableActive(v *bool) *RecurringExpenseUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *RecurringExpenseUpdateOne) SetStartDate(v time.Time) *RecurringExpenseUpdateOne {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *RecurringExpenseUpdateOne) SetNillableStartDate(v *time.Time) *RecurringExpenseUpdateOne {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *RecurringExpenseUpdateOne) SetEndDate(v time.Time) *RecurringExpenseUpdateOne {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *RecurringExpenseUpdateOne) SetNillableEndDate(v *time.Time) *RecurringExpenseUpdateOne {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// ClearEndDate clears the value of the "end_date" field.
func (_u *RecurringExpenseUpdateOne) ClearEndDate() *RecurringExpenseUpdateOne {
	_u.mutation.ClearEndDate()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RecurringExpenseUpdateOne) SetUpdatedAt(v time.Time) *RecurringExpenseUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetHouseholdID sets the "household" edge to the Household entity by ID.
func (_u *RecurringExpenseUpdateOne) SetHouseholdID(id int) *RecurringExpenseUpdateOne {
	_u.mutation.SetHouseholdID(id)
	return _u
}

// SetHousehold sets the "household" edge to the Household entity.
func (_u *RecurringExpenseUpdateOne) SetHousehold(v *Household) *RecurringExpenseUpdateOne {
	return _u.SetHouseholdID(v.ID)
}

// SetCategoryID sets the "category" edge to the Category entity by ID.
func (_u *RecurringExpenseUpdateOne) SetCategoryID(id int) *RecurringExpenseUpdateOne {
	_u.mutation.SetCategoryID(id)
	return _u
}

// SetCategory sets the "category" edge to the Category entity.
func (_u *RecurringExpenseUpdateOne) SetCategory(v *Category) *RecurringExpenseUpdateOne {
	return _u.SetCategoryID(v.ID)
}

// Mutation returns the RecurringExpenseMutation object of the builder.
func (_u *RecurringExpenseUpdateOne) Mutation() *RecurringExpenseMutation {
	return _u.mutation
}

// ClearHousehold clears the "household" edge to the Household entity.
func (_u *RecurringExpenseUpdateOne) ClearHousehold() *RecurringExpenseUpdateOne {
	_u.mutation.ClearHousehold()
	return _u
}

// ClearCategory clears the "category" edge to the Category entity.
func (_u *RecurringExpenseUpdateOne) ClearCategory() *RecurringExpenseUpdateOne {
	_u.mutation.ClearCategory()
	return _u
}

// Where appends a list predicates to the RecurringExpenseUpdate builder.
func (_u *RecurringExpenseUpdateOne) Where(ps ...predicate.RecurringExpense) *RecurringExpenseUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RecurringExpenseUpdateOne) Select(field string, fields ...string) *RecurringExpenseUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RecurringExpense entity.
func (_u *RecurringExpenseUpdateOne) Save(ctx context.Context) (*RecurringExpense, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RecurringExpenseUpdateOne) SaveX(ctx context.Context) *RecurringExpense {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RecurringExpenseUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RecurringExpenseUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RecurringExpenseUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := recurringexpense.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RecurringExpenseUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := recurringexpense.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RecurringExpense.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Amount(); ok {
		if err := recurringexpense.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "RecurringExpense.amount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Frequency(); ok {
		if err := recurringexpense.FrequencyValidator(v); err != nil {
			return &ValidationError{Name: "frequency", err: fmt.Errorf(`ent: validator failed for field "RecurringExpense.frequency": %w`, err)}
		}
	}
	if _u.mutation.HouseholdCleared() && len(_u.mutation.HouseholdIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RecurringExpense.household"`)
	}
	if _u.mutation.CategoryCleared() && len(_u.mutation.CategoryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RecurringExpense.category"`)
	}
	return nil
}

func (_u *RecurringExpenseUpdateOne) sqlSave(ctx context.Context) (_node *RecurringExpense, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(recurringexpense.Table, recurringexpense.Columns, sqlgraph.NewFieldSpec(recurringexpense.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RecurringExpense.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, recurringexpense.FieldID)
		for _, f := range fields {
			if !recurringexpense.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != recurringexpense.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(recurringexpense.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(recurringexpense.FieldAmount, field.TypeString, value)
	}
	if value, ok := _u.mutation.Frequency(); ok {
		_spec.SetField(recurringexpense.FieldFrequency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(recurringexpense.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(recurringexpense.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(recurringexpense.FieldEndDate, field.TypeTime, value)
	}
	if _u.mutation.EndDateCleared() {
		_spec.ClearField(recurringexpense.FieldEndDate, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(recurringexpense.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.HouseholdCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringexpense.HouseholdTable,
			Columns: []string{recurringexpense.HouseholdColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(household.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HouseholdIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringexpense.HouseholdTable,
			Columns: []string{recurringexpense.HouseholdColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(household.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringexpense.CategoryTable,
			Columns: []string{recurringexpense.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringexpense.CategoryTable,
			Columns: []string{recurringexpense.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RecurringExpense{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{recurringexpense.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
