// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"icekalt.dev/money-tracker/ent/recurringexpense"
	"icekalt.dev/money-tracker/ent/recurringscheduleoverride"
)

// RecurringScheduleOverrideCreate is the builder for creating a RecurringScheduleOverride entity.
type RecurringScheduleOverrideCreate struct {
	config
	mutation *RecurringScheduleOverrideMutation
	hooks    []Hook
}

// SetEffectiveDate sets the "effective_date" field.
func (_c *RecurringScheduleOverrideCreate) SetEffectiveDate(v time.Time) *RecurringScheduleOverrideCreate {
	_c.mutation.SetEffectiveDate(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *RecurringScheduleOverrideCreate) SetAmount(v string) *RecurringScheduleOverrideCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetFrequency sets the "frequency" field.
func (_c *RecurringScheduleOverrideCreate) SetFrequency(v string) *RecurringScheduleOverrideCreate {
	_c.mutation.SetFrequency(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RecurringScheduleOverrideCreate) SetCreatedAt(v time.Time) *RecurringScheduleOverrideCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RecurringScheduleOverrideCreate) SetNillableCreatedAt(v *time.Time) *RecurringScheduleOverrideCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RecurringScheduleOverrideCreate) SetUpdatedAt(v time.Time) *RecurringScheduleOverrideCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RecurringScheduleOverrideCreate) SetNillableUpdatedAt(v *time.Time) *RecurringScheduleOverrideCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetRecurringExpenseID sets the "recurring_expense" edge to the RecurringExpense entity by ID.
func (_c *RecurringScheduleOverrideCreate) SetRecurringExpenseID(id int) *RecurringScheduleOverrideCreate {
	_c.mutation.SetRecurringExpenseID(id)
	return _c
}

// SetRecurringExpense sets the "recurring_expense" edge to the RecurringExpense entity.
func (_c *RecurringScheduleOverrideCreate) SetRecurringExpense(v *RecurringExpense) *RecurringScheduleOverrideCreate {
	return _c.SetRecurringExpenseID(v.ID)
}

// Mutation returns the RecurringScheduleOverrideMutation object of the builder.
func (_c *RecurringScheduleOverrideCreate) Mutation() *RecurringScheduleOverrideMutation {
	return _c.mutation
}

// Save creates the RecurringScheduleOverride in the database.
func (_c *RecurringScheduleOverrideCreate) Save(ctx context.Context) (*RecurringScheduleOverride, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RecurringScheduleOverrideCreate) SaveX(ctx context.Context) *RecurringScheduleOverride {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RecurringScheduleOverrideCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RecurringScheduleOverrideCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RecurringScheduleOverrideCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := recurringscheduleoverride.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := recurringscheduleoverride.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RecurringScheduleOverrideCreate) check() error {
	if _, ok := _c.mutation.EffectiveDate(); !ok {
		return &ValidationError{Name: "effective_date", err: errors.New(`ent: missing required field "RecurringScheduleOverride.effective_date"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "RecurringScheduleOverride.amount"`)}
	}
	if v, ok := _c.mutation.Amount(); ok {
		if err := recurringscheduleoverride.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "RecurringScheduleOverride.amount": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Frequency(); !ok {
		return &ValidationError{Name: "frequency", err: errors.New(`ent: missing required field "RecurringScheduleOverride.frequency"`)}
	}
	if v, ok := _c.mutation.Frequency(); ok {
		if err := recurringscheduleoverride.FrequencyValidator(v); err != nil {
			return &ValidationError{Name: "frequency", err: fmt.Errorf(`ent: validator failed for field "RecurringScheduleOverride.frequency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RecurringScheduleOverride.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RecurringScheduleOverride.updated_at"`)}
	}
	if len(_c.mutation.RecurringExpenseIDs()) == 0 {
		return &ValidationError{Name: "recurring_expense", err: errors.New(`ent: missing required edge "RecurringScheduleOverride.recurring_expense"`)}
	}
	return nil
}

func (_c *RecurringScheduleOverrideCreate) sqlSave(ctx context.Context) (*RecurringScheduleOverride, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RecurringScheduleOverrideCreate) createSpec() (*RecurringScheduleOverride, *sqlgraph.CreateSpec) {
	var (
		_node = &RecurringScheduleOverride{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(recurringscheduleoverride.Table, sqlgraph.NewFieldSpec(recurringscheduleoverride.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.EffectiveDate(); ok {
		_spec.SetField(recurringscheduleoverride.FieldEffectiveDate, field.TypeTime, value)
		_node.EffectiveDate = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(recurringscheduleoverride.FieldAmount, field.TypeString, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Frequency(); ok {
		_spec.SetField(recurringscheduleoverride.FieldFrequency, field.TypeString, value)
		_node.Frequency = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(recurringscheduleoverride.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(recurringscheduleoverride.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.RecurringExpenseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringscheduleoverride.RecurringExpenseTable,
			Columns: []string{recurringscheduleoverride.RecurringExpenseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringexpense.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.recurring_expense_schedule_overrides = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RecurringScheduleOverrideCreateBulk is the builder for creating many RecurringScheduleOverride entities in bulk.
type RecurringScheduleOverrideCreateBulk struct {
	config
	err      error
	builders []*RecurringScheduleOverrideCreate
}

// Save creates the RecurringScheduleOverride entities in the database.
func (_c *RecurringScheduleOverrideCreateBulk) Save(ctx context.Context) ([]*RecurringScheduleOverride, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RecurringScheduleOverride, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RecurringScheduleOverrideMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RecurringScheduleOverrideCreateBulk) SaveX(ctx context.Context) []*RecurringScheduleOverride {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RecurringScheduleOverrideCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RecurringScheduleOverrideCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
