// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"icekalt.dev/money-tracker/ent/recurringexpense"
	"icekalt.dev/money-tracker/ent/recurringscheduleoverride"
)

// RecurringScheduleOverride is the model entity for the RecurringScheduleOverride schema.
type RecurringScheduleOverride struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// EffectiveDate holds the value of the "effective_date" field.
	EffectiveDate time.Time `json:"effective_date,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount string `json:"amount,omitempty"`
	// Frequency holds the value of the "frequency" field.
	Frequency string `json:"frequency,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RecurringScheduleOverrideQuery when eager-loading is set.
	Edges                                RecurringScheduleOverrideEdges `json:"edges"`
	recurring_expense_schedule_overrides *int
	selectValues                         sql.SelectValues
}

// RecurringScheduleOverrideEdges holds the relations/edges for other nodes in the graph.
type RecurringScheduleOverrideEdges struct {
	// RecurringExpense holds the value of the recurring_expense edge.
	RecurringExpense *RecurringExpense `json:"recurring_expense,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RecurringExpenseOrErr returns the RecurringExpense value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RecurringScheduleOverrideEdges) RecurringExpenseOrErr() (*RecurringExpense, error) {
	if e.RecurringExpense != nil {
		return e.RecurringExpense, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: recurringexpense.Label}
	}
	return nil, &NotLoadedError{edge: "recurring_expense"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RecurringScheduleOverride) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case recurringscheduleoverride.FieldID:
			values[i] = new(sql.NullInt64)
		case recurringscheduleoverride.FieldAmount, recurringscheduleoverride.FieldFrequency:
			values[i] = new(sql.NullString)
		case recurringscheduleoverride.FieldEffectiveDate, recurringscheduleoverride.FieldCreatedAt, recurringscheduleoverride.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case recurringscheduleoverride.ForeignKeys[0]: // recurring_expense_schedule_overrides
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RecurringScheduleOverride fields.
func (_m *RecurringScheduleOverride) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case recurringscheduleoverride.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case recurringscheduleoverride.FieldEffectiveDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field effective_date", values[i])
			} else if value.Valid {
				_m.EffectiveDate = value.Time
			}
		case recurringscheduleoverride.FieldAmount:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.String
			}
		case recurringscheduleoverride.FieldFrequency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field frequency", values[i])
			} else if value.Valid {
				_m.Frequency = value.String
			}
		case recurringscheduleoverride.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case recurringscheduleoverride.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case recurringscheduleoverride.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field recurring_expense_schedule_overrides", value)
			} else if value.Valid {
				_m.recurring_expense_schedule_overrides = new(int)
				*_m.recurring_expense_schedule_overrides = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RecurringScheduleOverride.
// This includes values selected through modifiers, order, etc.
func (_m *RecurringScheduleOverride) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRecurringExpense queries the "recurring_expense" edge of the RecurringScheduleOverride entity.
func (_m *RecurringScheduleOverride) QueryRecurringExpense() *RecurringExpenseQuery {
	return NewRecurringScheduleOverrideClient(_m.config).QueryRecurringExpense(_m)
}

// Update returns a builder for updating this RecurringScheduleOverride.
// Note that you need to call RecurringScheduleOverride.Unwrap() before calling this method if this RecurringScheduleOverride
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RecurringScheduleOverride) Update() *RecurringScheduleOverrideUpdateOne {
	return NewRecurringScheduleOverrideClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RecurringScheduleOverride entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RecurringScheduleOverride) Unwrap() *RecurringScheduleOverride {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RecurringScheduleOverride is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RecurringScheduleOverride) String() string {
	var builder strings.Builder
	builder.WriteString("RecurringScheduleOverride(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("effective_date=")
	builder.WriteString(_m.EffectiveDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(_m.Amount)
	builder.WriteString(", ")
	builder.WriteString("frequency=")
	builder.WriteString(_m.Frequency)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RecurringScheduleOverrides is a parsable slice of RecurringScheduleOverride.
type RecurringScheduleOverrides []*RecurringScheduleOverride
