// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"icekalt.dev/money-tracker/ent/category"
	"icekalt.dev/money-tracker/ent/household"
	"icekalt.dev/money-tracker/ent/predicate"
	"icekalt.dev/money-tracker/ent/recurringexpense"
)

// RecurringExpenseQuery is the builder for querying RecurringExpense entities.
type RecurringExpenseQuery struct {
	config
	ctx           *QueryContext
	order         []recurringexpense.OrderOption
	inters        []Interceptor
	predicates    []predicate.RecurringExpense
	withHousehold *HouseholdQuery
	withCategory  *CategoryQuery
	withFKs       bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RecurringExpenseQuery builder.
func (_q *RecurringExpenseQuery) Where(ps ...predicate.RecurringExpense) *RecurringExpenseQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *RecurringExpenseQuery) Limit(limit int) *RecurringExpenseQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *RecurringExpenseQuery) Offset(offset int) *RecurringExpenseQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *RecurringExpenseQuery) Unique(unique bool) *RecurringExpenseQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *RecurringExpenseQuery) Order(o ...recurringexpense.OrderOption) *RecurringExpenseQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryHousehold chains the current query on the "household" edge.
func (_q *RecurringExpenseQuery) QueryHousehold() *HouseholdQuery {
	query := (&HouseholdClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(recurringexpense.Table, recurringexpense.FieldID, selector),
			sqlgraph.To(household.Table, household.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, recurringexpense.HouseholdTable, recurringexpense.HouseholdColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCategory chains the current query on the "category" edge.
func (_q *RecurringExpenseQuery) QueryCategory() *CategoryQuery {
	query := (&CategoryClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(recurringexpense.Table, recurringexpense.FieldID, selector),
			sqlgraph.To(category.Table, category.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, recurringexpense.CategoryTable, recurringexpense.CategoryColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RecurringExpense entity from the query.
// Returns a *NotFoundError when no RecurringExpense was found.
func (_q *RecurringExpenseQuery) First(ctx context.Context) (*RecurringExpense, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{recurringexpense.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *RecurringExpenseQuery) FirstX(ctx context.Context) *RecurringExpense {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RecurringExpense ID from the query.
// Returns a *NotFoundError when no RecurringExpense ID was found.
func (_q *RecurringExpenseQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{recurringexpense.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *RecurringExpenseQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RecurringExpense entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RecurringExpense entity is found.
// Returns a *NotFoundError when no RecurringExpense entities are found.
func (_q *RecurringExpenseQuery) Only(ctx context.Context) (*RecurringExpense, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{recurringexpense.Label}
	default:
		return nil, &NotSingularError{recurringexpense.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *RecurringExpenseQuery) OnlyX(ctx context.Context) *RecurringExpense {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RecurringExpense ID in the query.
// Returns a *NotSingularError when more than one RecurringExpense ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *RecurringExpenseQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{recurringexpense.Label}
	default:
		err = &NotSingularError{recurringexpense.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *RecurringExpenseQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RecurringExpenses.
func (_q *RecurringExpenseQuery) All(ctx context.Context) ([]*RecurringExpense, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RecurringExpense, *RecurringExpenseQuery]()
	return withInterceptors[[]*RecurringExpense](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *RecurringExpenseQuery) AllX(ctx context.Context) []*RecurringExpense {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RecurringExpense IDs.
func (_q *RecurringExpenseQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(recurringexpense.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *RecurringExpenseQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *RecurringExpenseQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*RecurringExpenseQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *RecurringExpenseQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *RecurringExpenseQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *RecurringExpenseQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RecurringExpenseQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *RecurringExpenseQuery) Clone() *RecurringExpenseQuery {
	if _q == nil {
		return nil
	}
	return &RecurringExpenseQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]recurringexpense.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.RecurringExpense{}, _q.predicates...),
		withHousehold: _q.withHousehold.Clone(),
		withCategory:  _q.withCategory.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithHousehold tells the query-builder to eager-load the nodes that are connected to
// the "household" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RecurringExpenseQuery) WithHousehold(opts ...func(*HouseholdQuery)) *RecurringExpenseQuery {
	query := (&HouseholdClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withHousehold = query
	return _q
}

// WithCategory tells the query-builder to eager-load the nodes that are connected to
// the "category" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RecurringExpenseQuery) WithCategory(opts ...func(*CategoryQuery)) *RecurringExpenseQuery {
	query := (&CategoryClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCategory = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RecurringExpense.Query().
//		GroupBy(recurringexpense.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *RecurringExpenseQuery) GroupBy(field string, fields ...string) *RecurringExpenseGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RecurringExpenseGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = recurringexpense.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.RecurringExpense.Query().
//		Select(recurringexpense.FieldName).
//		Scan(ctx, &v)
func (_q *RecurringExpenseQuery) Select(fields ...string) *RecurringExpenseSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &RecurringExpenseSelect{RecurringExpenseQuery: _q}
	sbuild.label = recurringexpense.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RecurringExpenseSelect configured with the given aggregations.
func (_q *RecurringExpenseQuery) Aggregate(fns ...AggregateFunc) *RecurringExpenseSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *RecurringExpenseQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !recurringexpense.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *RecurringExpenseQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RecurringExpense, error) {
	var (
		nodes       = []*RecurringExpense{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withHousehold != nil,
			_q.withCategory != nil,
		}
	)
	if _q.withHousehold != nil || _q.withCategory != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, recurringexpense.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RecurringExpense).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RecurringExpense{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withHousehold; query != nil {
		if err := _q.loadHousehold(ctx, query, nodes, nil,
			func(n *RecurringExpense, e *Household) { n.Edges.Household = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCategory; query != nil {
		if err := _q.loadCategory(ctx, query, nodes, nil,
			func(n *RecurringExpense, e *Category) { n.Edges.Category = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *RecurringExpenseQuery) loadHousehold(ctx context.Context, query *HouseholdQuery, nodes []*RecurringExpense, init func(*RecurringExpense), assign func(*RecurringExpense, *Household)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*RecurringExpense)
	for i := range nodes {
		if nodes[i].household_recurring_expenses == nil {
			continue
		}
		fk := *nodes[i].household_recurring_expenses
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(household.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "household_recurring_expenses" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *RecurringExpenseQuery) loadCategory(ctx context.Context, query *CategoryQuery, nodes []*RecurringExpense, init func(*RecurringExpense), assign func(*RecurringExpense, *Category)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*RecurringExpense)
	for i := range nodes {
		if nodes[i].category_recurring_expenses == nil {
			continue
		}
		fk := *nodes[i].category_recurring_expenses
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(category.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "category_recurring_expenses" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *RecurringExpenseQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *RecurringExpenseQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(recurringexpense.Table, recurringexpense.Columns, sqlgraph.NewFieldSpec(recurringexpense.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, recurringexpense.FieldID)
		for i := range fields {
			if fields[i] != recurringexpense.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *RecurringExpenseQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(recurringexpense.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = recurringexpense.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RecurringExpenseGroupBy is the group-by builder for RecurringExpense entities.
type RecurringExpenseGroupBy struct {
	selector
	build *RecurringExpenseQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *RecurringExpenseGroupBy) Aggregate(fns ...AggregateFunc) *RecurringExpenseGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *RecurringExpenseGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RecurringExpenseQuery, *RecurringExpenseGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *RecurringExpenseGroupBy) sqlScan(ctx context.Context, root *RecurringExpenseQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RecurringExpenseSelect is the builder for selecting fields of RecurringExpense entities.
type RecurringExpenseSelect struct {
	*RecurringExpenseQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *RecurringExpenseSelect) Aggregate(fns ...AggregateFunc) *RecurringExpenseSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *RecurringExpenseSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RecurringExpenseQuery, *RecurringExpenseSelect](ctx, _s.RecurringExpenseQuery, _s, _s.inters, v)
}

func (_s *RecurringExpenseSelect) sqlScan(ctx context.Context, root *RecurringExpenseQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
