// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"icekalt.dev/money-tracker/ent/predicate"
	"icekalt.dev/money-tracker/ent/recurringexpense"
	"icekalt.dev/money-tracker/ent/recurringscheduleoverride"
)

// RecurringScheduleOverrideUpdate is the builder for updating RecurringScheduleOverride entities.
type RecurringScheduleOverrideUpdate struct {
	config
	hooks    []Hook
	mutation *RecurringScheduleOverrideMutation
}

// Where appends a list predicates to the RecurringScheduleOverrideUpdate builder.
func (_u *RecurringScheduleOverrideUpdate) Where(ps ...predicate.RecurringScheduleOverride) *RecurringScheduleOverrideUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEffectiveDate sets the "effective_date" field.
func (_u *RecurringScheduleOverrideUpdate) SetEffectiveDate(v time.Time) *RecurringScheduleOverrideUpdate {
	_u.mutation.SetEffectiveDate(v)
	return _u
}

// SetNillableEffectiveDate sets the "effective_date" field if the given value is not nil.
func (_u *RecurringScheduleOverrideUpdate) SetNillableEffectiveDate(v *time.Time) *RecurringScheduleOverrideUpdate {
	if v != nil {
		_u.SetEffectiveDate(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *RecurringScheduleOverrideUpdate) SetAmount(v string) *RecurringScheduleOverrideUpdate {
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *RecurringScheduleOverrideUpdate) SetNillableAmount(v *string) *RecurringScheduleOverrideUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// SetFrequency sets the "frequency" field.
func (_u *RecurringScheduleOverrideUpdate) SetFrequency(v string) *RecurringScheduleOverrideUpdate {
	_u.mutation.SetFrequency(v)
	return _u
}

// SetNillableFrequency sets the "frequency" field if the given value is not nil.
func (_u *RecurringScheduleOverrideUpdate) SetNillableFrequency(v *string) *RecurringScheduleOverrideUpdate {
	if v != nil {
		_u.SetFrequency(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RecurringScheduleOverrideUpdate) SetUpdatedAt(v time.Time) *RecurringScheduleOverrideUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRecurringExpenseID sets the "recurring_expense" edge to the RecurringExpense entity by ID.
func (_u *RecurringScheduleOverrideUpdate) SetRecurringExpenseID(id int) *RecurringScheduleOverrideUpdate {
	_u.mutation.SetRecurringExpenseID(id)
	return _u
}

// SetRecurringExpense sets the "recurring_expense" edge to the RecurringExpense entity.
func (_u *RecurringScheduleOverrideUpdate) SetRecurringExpense(v *RecurringExpense) *RecurringScheduleOverrideUpdate {
	return _u.SetRecurringExpenseID(v.ID)
}

// Mutation returns the RecurringScheduleOverrideMutation object of the builder.
func (_u *RecurringScheduleOverrideUpdate) Mutation() *RecurringScheduleOverrideMutation {
	return _u.mutation
}

// ClearRecurringExpense clears the "recurring_expense" edge to the RecurringExpense entity.
func (_u *RecurringScheduleOverrideUpdate) ClearRecurringExpense() *RecurringScheduleOverrideUpdate {
	_u.mutation.ClearRecurringExpense()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RecurringScheduleOverrideUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RecurringScheduleOverrideUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RecurringScheduleOverrideUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RecurringScheduleOverrideUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RecurringScheduleOverrideUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := recurringscheduleoverride.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RecurringScheduleOverrideUpdate) check() error {
	if v, ok := _u.mutation.Amount(); ok {
		if err := recurringscheduleoverride.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "RecurringScheduleOverride.amount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Frequency(); ok {
		if err := recurringscheduleoverride.FrequencyValidator(v); err != nil {
			return &ValidationError{Name: "frequency", err: fmt.Errorf(`ent: validator failed for field "RecurringScheduleOverride.frequency": %w`, err)}
		}
	}
	if _u.mutation.RecurringExpenseCleared() && len(_u.mutation.RecurringExpenseIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RecurringScheduleOverride.recurring_expense"`)
	}
	return nil
}

func (_u *RecurringScheduleOverrideUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(recurringscheduleoverride.Table, recurringscheduleoverride.Columns, sqlgraph.NewFieldSpec(recurringscheduleoverride.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EffectiveDate(); ok {
		_spec.SetField(recurringscheduleoverride.FieldEffectiveDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(recurringscheduleoverride.FieldAmount, field.TypeString, value)
	}
	if value, ok := _u.mutation.Frequency(); ok {
		_spec.SetField(recurringscheduleoverride.FieldFrequency, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(recurringscheduleoverride.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RecurringExpenseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringscheduleoverride.RecurringExpenseTable,
			Columns: []string{recurringscheduleoverride.RecurringExpenseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringexpense.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecurringExpenseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringscheduleoverride.RecurringExpenseTable,
			Columns: []string{recurringscheduleoverride.RecurringExpenseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringexpense.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{recurringscheduleoverride.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RecurringScheduleOverrideUpdateOne is the builder for updating a single RecurringScheduleOverride entity.
type RecurringScheduleOverrideUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RecurringScheduleOverrideMutation
}

// SetEffectiveDate sets the "effective_date" field.
func (_u *RecurringScheduleOverrideUpdateOne) SetEffectiveDate(v time.Time) *RecurringScheduleOverrideUpdateOne {
	_u.mutation.SetEffectiveDate(v)
	return _u
}

// SetNillableEffectiveDate sets the "effective_date" field if the given value is not nil.
func (_u *RecurringScheduleOverrideUpdateOne) SetNillableEffectiveDate(v *time.Time) *RecurringScheduleOverrideUpdateOne {
	if v != nil {
		_u.SetEffectiveDate(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *RecurringScheduleOverrideUpdateOne) SetAmount(v string) *RecurringScheduleOverrideUpdateOne {
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *RecurringScheduleOverrideUpdateOne) SetNillableAmount(v *string) *RecurringScheduleOverrideUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// SetFrequency sets the "frequency" field.
func (_u *RecurringScheduleOverrideUpdateOne) SetFrequency(v string) *RecurringScheduleOverrideUpdateOne {
	_u.mutation.SetFrequency(v)
	return _u
}

// SetNillableFrequency sets the "frequency" field if the given value is not nil.
func (_u *RecurringScheduleOverrideUpdateOne) SetNillableFrequency(v *string) *RecurringScheduleOverrideUpdateOne {
	if v != nil {
		_u.SetFrequency(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RecurringScheduleOverrideUpdateOne) SetUpdatedAt(v time.Time) *RecurringScheduleOverrideUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRecurringExpenseID sets the "recurring_expense" edge to the RecurringExpense entity by ID.
func (_u *RecurringScheduleOverrideUpdateOne) SetRecurringExpenseID(id int) *RecurringScheduleOverrideUpdateOne {
	_u.mutation.SetRecurringExpenseID(id)
	return _u
}

// SetRecurringExpense sets the "recurring_expense" edge to the RecurringExpense entity.
func (_u *RecurringScheduleOverrideUpdateOne) SetRecurringExpense(v *RecurringExpense) *RecurringScheduleOverrideUpdateOne {
	return _u.SetRecurringExpenseID(v.ID)
}

// Mutation returns the RecurringScheduleOverrideMutation object of the builder.
func (_u *RecurringScheduleOverrideUpdateOne) Mutation() *RecurringScheduleOverrideMutation {
	return _u.mutation
}

// ClearRecurringExpense clears the "recurring_expense" edge to the RecurringExpense entity.
func (_u *RecurringScheduleOverrideUpdateOne) ClearRecurringExpense() *RecurringScheduleOverrideUpdateOne {
	_u.mutation.ClearRecurringExpense()
	return _u
}

// Where appends a list predicates to the RecurringScheduleOverrideUpdate builder.
func (_u *RecurringScheduleOverrideUpdateOne) Where(ps ...predicate.RecurringScheduleOverride) *RecurringScheduleOverrideUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RecurringScheduleOverrideUpdateOne) Select(field string, fields ...string) *RecurringScheduleOverrideUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RecurringScheduleOverride entity.
func (_u *RecurringScheduleOverrideUpdateOne) Save(ctx context.Context) (*RecurringScheduleOverride, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RecurringScheduleOverrideUpdateOne) SaveX(ctx context.Context) *RecurringScheduleOverride {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RecurringScheduleOverrideUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RecurringScheduleOverrideUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RecurringScheduleOverrideUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := recurringscheduleoverride.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RecurringScheduleOverrideUpdateOne) check() error {
	if v, ok := _u.mutation.Amount(); ok {
		if err := recurringscheduleoverride.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "RecurringScheduleOverride.amount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Frequency(); ok {
		if err := recurringscheduleoverride.FrequencyValidator(v); err != nil {
			return &ValidationError{Name: "frequency", err: fmt.Errorf(`ent: validator failed for field "RecurringScheduleOverride.frequency": %w`, err)}
		}
	}
	if _u.mutation.RecurringExpenseCleared() && len(_u.mutation.RecurringExpenseIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RecurringScheduleOverride.recurring_expense"`)
	}
	return nil
}

func (_u *RecurringScheduleOverrideUpdateOne) sqlSave(ctx context.Context) (_node *RecurringScheduleOverride, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(recurringscheduleoverride.Table, recurringscheduleoverride.Columns, sqlgraph.NewFieldSpec(recurringscheduleoverride.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RecurringScheduleOverride.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, recurringscheduleoverride.FieldID)
		for _, f := range fields {
			if !recurringscheduleoverride.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != recurringscheduleoverride.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EffectiveDate(); ok {
		_spec.SetField(recurringscheduleoverride.FieldEffectiveDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(recurringscheduleoverride.FieldAmount, field.TypeString, value)
	}
	if value, ok := _u.mutation.Frequency(); ok {
		_spec.SetField(recurringscheduleoverride.FieldFrequency, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(recurringscheduleoverride.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RecurringExpenseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringscheduleoverride.RecurringExpenseTable,
			Columns: []string{recurringscheduleoverride.RecurringExpenseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringexpense.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecurringExpenseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringscheduleoverride.RecurringExpenseTable,
			Columns: []string{recurringscheduleoverride.RecurringExpenseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringexpense.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RecurringScheduleOverride{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{recurringscheduleoverride.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
