// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"icekalt.dev/money-tracker/ent/apitoken"
	"icekalt.dev/money-tracker/ent/category"
	"icekalt.dev/money-tracker/ent/household"
	"icekalt.dev/money-tracker/ent/recurringexpense"
	"icekalt.dev/money-tracker/ent/schema"
	"icekalt.dev/money-tracker/ent/transaction"
	"icekalt.dev/money-tracker/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	apitokenFields := schema.APIToken{}.Fields()
	_ = apitokenFields
	// apitokenDescName is the schema descriptor for name field.
	apitokenDescName := apitokenFields[0].Descriptor()
	// apitoken.NameValidator is a validator for the "name" field. It is called by the builders before save.
	apitoken.NameValidator = func() func(string) error {
		validators := apitokenDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// apitokenDescTokenHash is the schema descriptor for token_hash field.
	apitokenDescTokenHash := apitokenFields[1].Descriptor()
	// apitoken.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	apitoken.TokenHashValidator = apitokenDescTokenHash.Validators[0].(func(string) error)
	// apitokenDescCreatedAt is the schema descriptor for created_at field.
	apitokenDescCreatedAt := apitokenFields[4].Descriptor()
	// apitoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	apitoken.DefaultCreatedAt = apitokenDescCreatedAt.Default.(func() time.Time)
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescName is the schema descriptor for name field.
	categoryDescName := categoryFields[0].Descriptor()
	// category.NameValidator is a validator for the "name" field. It is called by the builders before save.
	category.NameValidator = func() func(string) error {
		validators := categoryDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// categoryDescIcon is the schema descriptor for icon field.
	categoryDescIcon := categoryFields[1].Descriptor()
	// category.DefaultIcon holds the default value on creation for the icon field.
	category.DefaultIcon = categoryDescIcon.Default.(string)
	// category.IconValidator is a validator for the "icon" field. It is called by the builders before save.
	category.IconValidator = categoryDescIcon.Validators[0].(func(string) error)
	// categoryDescCreatedAt is the schema descriptor for created_at field.
	categoryDescCreatedAt := categoryFields[2].Descriptor()
	// category.DefaultCreatedAt holds the default value on creation for the created_at field.
	category.DefaultCreatedAt = categoryDescCreatedAt.Default.(func() time.Time)
	// categoryDescUpdatedAt is the schema descriptor for updated_at field.
	categoryDescUpdatedAt := categoryFields[3].Descriptor()
	// category.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	category.DefaultUpdatedAt = categoryDescUpdatedAt.Default.(func() time.Time)
	// category.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	category.UpdateDefaultUpdatedAt = categoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	householdFields := schema.Household{}.Fields()
	_ = householdFields
	// householdDescName is the schema descriptor for name field.
	householdDescName := householdFields[0].Descriptor()
	// household.NameValidator is a validator for the "name" field. It is called by the builders before save.
	household.NameValidator = func() func(string) error {
		validators := householdDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// householdDescCurrency is the schema descriptor for currency field.
	householdDescCurrency := householdFields[1].Descriptor()
	// household.DefaultCurrency holds the default value on creation for the currency field.
	household.DefaultCurrency = householdDescCurrency.Default.(string)
	// household.CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	household.CurrencyValidator = func() func(string) error {
		validators := householdDescCurrency.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(currency string) error {
			for _, fn := range fns {
				if err := fn(currency); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// householdDescIcon is the schema descriptor for icon field.
	householdDescIcon := householdFields[2].Descriptor()
	// household.DefaultIcon holds the default value on creation for the icon field.
	household.DefaultIcon = householdDescIcon.Default.(string)
	// household.IconValidator is a validator for the "icon" field. It is called by the builders before save.
	household.IconValidator = householdDescIcon.Validators[0].(func(string) error)
	// householdDescCreatedAt is the schema descriptor for created_at field.
	householdDescCreatedAt := householdFields[3].Descriptor()
	// household.DefaultCreatedAt holds the default value on creation for the created_at field.
	household.DefaultCreatedAt = householdDescCreatedAt.Default.(func() time.Time)
	// householdDescUpdatedAt is the schema descriptor for updated_at field.
	householdDescUpdatedAt := householdFields[4].Descriptor()
	// household.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	household.DefaultUpdatedAt = householdDescUpdatedAt.Default.(func() time.Time)
	// household.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	household.UpdateDefaultUpdatedAt = householdDescUpdatedAt.UpdateDefault.(func() time.Time)
	recurringexpenseFields := schema.RecurringExpense{}.Fields()
	_ = recurringexpenseFields
	// recurringexpenseDescName is the schema descriptor for name field.
	recurringexpenseDescName := recurringexpenseFields[0].Descriptor()
	// recurringexpense.NameValidator is a validator for the "name" field. It is called by the builders before save.
	recurringexpense.NameValidator = func() func(string) error {
		validators := recurringexpenseDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// recurringexpenseDescDescription is the schema descriptor for description field.
	recurringexpenseDescDescription := recurringexpenseFields[1].Descriptor()
	// recurringexpense.DefaultDescription holds the default value on creation for the description field.
	recurringexpense.DefaultDescription = recurringexpenseDescDescription.Default.(string)
	// recurringexpense.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	recurringexpense.DescriptionValidator = recurringexpenseDescDescription.Validators[0].(func(string) error)
	// recurringexpenseDescAmount is the schema descriptor for amount field.
	recurringexpenseDescAmount := recurringexpenseFields[2].Descriptor()
	// recurringexpense.AmountValidator is a validator for the "amount" field. It is called by the builders before save.
	recurringexpense.AmountValidator = recurringexpenseDescAmount.Validators[0].(func(string) error)
	// recurringexpenseDescFrequency is the schema descriptor for frequency field.
	recurringexpenseDescFrequency := recurringexpenseFields[3].Descriptor()
	// recurringexpense.FrequencyValidator is a validator for the "frequency" field. It is called by the builders before save.
	recurringexpense.FrequencyValidator = recurringexpenseDescFrequency.Validators[0].(func(string) error)
	// recurringexpenseDescActive is the schema descriptor for active field.
	recurringexpenseDescActive := recurringexpenseFields[4].Descriptor()
	// recurringexpense.DefaultActive holds the default value on creation for the active field.
	recurringexpense.DefaultActive = recurringexpenseDescActive.Default.(bool)
	// recurringexpenseDescCreatedAt is the schema descriptor for created_at field.
	recurringexpenseDescCreatedAt := recurringexpenseFields[7].Descriptor()
	// recurringexpense.DefaultCreatedAt holds the default value on creation for the created_at field.
	recurringexpense.DefaultCreatedAt = recurringexpenseDescCreatedAt.Default.(func() time.Time)
	// recurringexpenseDescUpdatedAt is the schema descriptor for updated_at field.
	recurringexpenseDescUpdatedAt := recurringexpenseFields[8].Descriptor()
	// recurringexpense.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	recurringexpense.DefaultUpdatedAt = recurringexpenseDescUpdatedAt.Default.(func() time.Time)
	// recurringexpense.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	recurringexpense.UpdateDefaultUpdatedAt = recurringexpenseDescUpdatedAt.UpdateDefault.(func() time.Time)
	transactionFields := schema.Transaction{}.Fields()
	_ = transactionFields
	// transactionDescAmount is the schema descriptor for amount field.
	transactionDescAmount := transactionFields[0].Descriptor()
	// transaction.AmountValidator is a validator for the "amount" field. It is called by the builders before save.
	transaction.AmountValidator = transactionDescAmount.Validators[0].(func(string) error)
	// transactionDescDescription is the schema descriptor for description field.
	transactionDescDescription := transactionFields[1].Descriptor()
	// transaction.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	transaction.DescriptionValidator = transactionDescDescription.Validators[0].(func(string) error)
	// transactionDescCreatedAt is the schema descriptor for created_at field.
	transactionDescCreatedAt := transactionFields[3].Descriptor()
	// transaction.DefaultCreatedAt holds the default value on creation for the created_at field.
	transaction.DefaultCreatedAt = transactionDescCreatedAt.Default.(func() time.Time)
	// transactionDescUpdatedAt is the schema descriptor for updated_at field.
	transactionDescUpdatedAt := transactionFields[4].Descriptor()
	// transaction.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	transaction.DefaultUpdatedAt = transactionDescUpdatedAt.Default.(func() time.Time)
	// transaction.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	transaction.UpdateDefaultUpdatedAt = transactionDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[0].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescSubject is the schema descriptor for subject field.
	userDescSubject := userFields[2].Descriptor()
	// user.SubjectValidator is a validator for the "subject" field. It is called by the builders before save.
	user.SubjectValidator = userDescSubject.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[4].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
