// Code generated by ent, DO NOT EDIT.

package recurringscheduleoverride

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the recurringscheduleoverride type in the database.
	Label = "recurring_schedule_override"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEffectiveDate holds the string denoting the effective_date field in the database.
	FieldEffectiveDate = "effective_date"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldFrequency holds the string denoting the frequency field in the database.
	FieldFrequency = "frequency"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeRecurringExpense holds the string denoting the recurring_expense edge name in mutations.
	EdgeRecurringExpense = "recurring_expense"
	// Table holds the table name of the recurringscheduleoverride in the database.
	Table = "recurring_schedule_overrides"
	// RecurringExpenseTable is the table that holds the recurring_expense relation/edge.
	RecurringExpenseTable = "recurring_schedule_overrides"
	// RecurringExpenseInverseTable is the table name for the RecurringExpense entity.
	// It exists in this package in order to avoid circular dependency with the "recurringexpense" package.
	RecurringExpenseInverseTable = "recurring_expenses"
	// RecurringExpenseColumn is the table column denoting the recurring_expense relation/edge.
	RecurringExpenseColumn = "recurring_expense_schedule_overrides"
)

// Columns holds all SQL columns for recurringscheduleoverride fields.
var Columns = []string{
	FieldID,
	FieldEffectiveDate,
	FieldAmount,
	FieldFrequency,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "recurring_schedule_overrides"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"recurring_expense_schedule_overrides",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// AmountValidator is a validator for the "amount" field. It is called by the builders before save.
	AmountValidator func(string) error
	// FrequencyValidator is a validator for the "frequency" field. It is called by the builders before save.
	FrequencyValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the RecurringScheduleOverride queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEffectiveDate orders the results by the effective_date field.
func ByEffectiveDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEffectiveDate, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByFrequency orders the results by the frequency field.
func ByFrequency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFrequency, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByRecurringExpenseField orders the results by recurring_expense field.
func ByRecurringExpenseField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRecurringExpenseStep(), sql.OrderByField(field, opts...))
	}
}
func newRecurringExpenseStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RecurringExpenseInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RecurringExpenseTable, RecurringExpenseColumn),
	)
}
