// Code generated by ent, DO NOT EDIT.

package recurringscheduleoverride

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"icekalt.dev/money-tracker/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldLTE(FieldID, id))
}

// EffectiveDate applies equality check predicate on the "effective_date" field. It's identical to EffectiveDateEQ.
func EffectiveDate(v time.Time) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldEQ(FieldEffectiveDate, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v string) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldEQ(FieldAmount, v))
}

// Frequency applies equality check predicate on the "frequency" field. It's identical to FrequencyEQ.
func Frequency(v string) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldEQ(FieldFrequency, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldEQ(FieldUpdatedAt, v))
}

// EffectiveDateEQ applies the EQ predicate on the "effective_date" field.
func EffectiveDateEQ(v time.Time) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldEQ(FieldEffectiveDate, v))
}

// EffectiveDateNEQ applies the NEQ predicate on the "effective_date" field.
func EffectiveDateNEQ(v time.Time) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldNEQ(FieldEffectiveDate, v))
}

// EffectiveDateIn applies the In predicate on the "effective_date" field.
func EffectiveDateIn(vs ...time.Time) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldIn(FieldEffectiveDate, vs...))
}

// EffectiveDateNotIn applies the NotIn predicate on the "effective_date" field.
func EffectiveDateNotIn(vs ...time.Time) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldNotIn(FieldEffectiveDate, vs...))
}

// EffectiveDateGT applies the GT predicate on the "effective_date" field.
func EffectiveDateGT(v time.Time) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldGT(FieldEffectiveDate, v))
}

// EffectiveDateGTE applies the GTE predicate on the "effective_date" field.
func EffectiveDateGTE(v time.Time) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldGTE(FieldEffectiveDate, v))
}

// EffectiveDateLT applies the LT predicate on the "effective_date" field.
func EffectiveDateLT(v time.Time) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldLT(FieldEffectiveDate, v))
}

// EffectiveDateLTE applies the LTE predicate on the "effective_date" field.
func EffectiveDateLTE(v time.Time) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldLTE(FieldEffectiveDate, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v string) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v string) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...string) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...string) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v string) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v string) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v string) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v string) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldLTE(FieldAmount, v))
}

// AmountContains applies the Contains predicate on the "amount" field.
func AmountContains(v string) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldContains(FieldAmount, v))
}

// AmountHasPrefix applies the HasPrefix predicate on the "amount" field.
func AmountHasPrefix(v string) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldHasPrefix(FieldAmount, v))
}

// AmountHasSuffix applies the HasSuffix predicate on the "amount" field.
func AmountHasSuffix(v string) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldHasSuffix(FieldAmount, v))
}

// AmountEqualFold applies the EqualFold predicate on the "amount" field.
func AmountEqualFold(v string) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldEqualFold(FieldAmount, v))
}

// AmountContainsFold applies the ContainsFold predicate on the "amount" field.
func AmountContainsFold(v string) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldContainsFold(FieldAmount, v))
}

// FrequencyEQ applies the EQ predicate on the "frequency" field.
func FrequencyEQ(v string) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldEQ(FieldFrequency, v))
}

// FrequencyNEQ applies the NEQ predicate on the "frequency" field.
func FrequencyNEQ(v string) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldNEQ(FieldFrequency, v))
}

// FrequencyIn applies the In predicate on the "frequency" field.
func FrequencyIn(vs ...string) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldIn(FieldFrequency, vs...))
}

// FrequencyNotIn applies the NotIn predicate on the "frequency" field.
func FrequencyNotIn(vs ...string) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldNotIn(FieldFrequency, vs...))
}

// FrequencyGT applies the GT predicate on the "frequency" field.
func FrequencyGT(v string) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldGT(FieldFrequency, v))
}

// FrequencyGTE applies the GTE predicate on the "frequency" field.
func FrequencyGTE(v string) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldGTE(FieldFrequency, v))
}

// FrequencyLT applies the LT predicate on the "frequency" field.
func FrequencyLT(v string) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldLT(FieldFrequency, v))
}

// FrequencyLTE applies the LTE predicate on the "frequency" field.
func FrequencyLTE(v string) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldLTE(FieldFrequency, v))
}

// FrequencyContains applies the Contains predicate on the "frequency" field.
func FrequencyContains(v string) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldContains(FieldFrequency, v))
}

// FrequencyHasPrefix applies the HasPrefix predicate on the "frequency" field.
func FrequencyHasPrefix(v string) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldHasPrefix(FieldFrequency, v))
}

// FrequencyHasSuffix applies the HasSuffix predicate on the "frequency" field.
func FrequencyHasSuffix(v string) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldHasSuffix(FieldFrequency, v))
}

// FrequencyEqualFold applies the EqualFold predicate on the "frequency" field.
func FrequencyEqualFold(v string) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldEqualFold(FieldFrequency, v))
}

// FrequencyContainsFold applies the ContainsFold predicate on the "frequency" field.
func FrequencyContainsFold(v string) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldContainsFold(FieldFrequency, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasRecurringExpense applies the HasEdge predicate on the "recurring_expense" edge.
func HasRecurringExpense() predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RecurringExpenseTable, RecurringExpenseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRecurringExpenseWith applies the HasEdge predicate on the "recurring_expense" edge with a given conditions (other predicates).
func HasRecurringExpenseWith(preds ...predicate.RecurringExpense) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(func(s *sql.Selector) {
		step := newRecurringExpenseStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RecurringScheduleOverride) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RecurringScheduleOverride) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RecurringScheduleOverride) predicate.RecurringScheduleOverride {
	return predicate.RecurringScheduleOverride(sql.NotPredicates(p))
}
